from setuptools import setup, find_packages

with open('README.md', 'r', encoding='utf-8') as fh:
    long_description = fh.read()

from _version import __version__

setup(
    name='elm',
    version=__version__,
    description='A CLI interface for extracting LogicMonitor data via the API',
    long_description=long_description,
    long_description_content_type='text/markdown',
    url='https://github.com/rdmarsh/elm',
    author='David Marsh',
    author_email='rdmarsh@gmail.com',
    license='GPLv3',
    # elm.py (the entry point), engine.py and _version.py are top-level
    # modules, not a package, so they must be listed explicitly. find_packages()
    # alone would only pick up _cmds/ and silently omit the entry point.
    py_modules=['elm', 'engine', '_version'],
    # _cmds/ is the only package -- generated by `make render`.
    packages=find_packages(),
    # Runtime dependencies only. Build-time tools are pinned in requirements.txt,
    # not here: jinja2-cli renders the templates in `make render` and pyinstaller
    # builds the binary -- neither is imported by elm at runtime.
    install_requires=[
        'click_config_file~=0.6.0',
        'click~=7.1.2',
        'htmlmin2~=0.1.13',
        'lxml~=6.1',
        'pandas~=2.3',
        'Pygments~=2.20',
        'PySocks~=1.7.1',
        'requests~=2.33',
        'tabulate~=0.8.10',
        'truststore~=0.10',
    ],
    entry_points={
        'console_scripts': [
            'elm=elm:cli',  # Points to the cli() function in elm.py
        ],
    },
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.9',
)
